Revert "Revert "Merge pull request #24001 from MetaMask/Version-v11.15.0""
This reverts commit a262bb2da20a07f73c4e9102a0104548ef2a5f2f.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -67,6 +67,18 @@ aliases:
         git checkout -B "$CIRCLE_BRANCH" "$CIRCLE_SHA1"
       fi
 
+  # Check if MMI Optional tests should run
+  - &check-mmi-optional
+    name: Check if MMI Optional tests should run
+    command: |
+      RUN_MMI_OPTIONAL=$(cat ./RUN_MMI_OPTIONAL)
+      if [[ "${CIRCLE_BRANCH}" == "develop" || "${RUN_MMI_OPTIONAL}" == "true" ]]; then
+        echo "Running MMI Optional tests"
+      else
+        echo "Skipping MMI Optional tests"
+        circleci step halt
+      fi
+
 workflows:
   test_and_release:
     jobs:
@@ -77,6 +89,7 @@ workflows:
       - trigger-beta-build:
           requires:
             - prep-deps
+      - check-pr-tag
       - prep-deps
       - test-deps-audit:
           requires:
@@ -132,6 +145,7 @@ workflows:
       - prep-build-test-mmi-playwright:
           requires:
             - prep-deps
+            - check-pr-tag
       - prep-build-storybook:
           requires:
             - prep-deps
@@ -372,6 +386,68 @@ jobs:
       - run:
           name: Create GitHub Pull Request for version
           command: .circleci/scripts/release-create-release-pr.sh
+
+  check-pr-tag:
+    docker:
+      - image: cimg/base:stable
+    steps:
+      - run:
+          name: Check for MMI Team Tag
+          command: |
+            #!/bin/bash
+
+            # GitHub Personal Access Token for API Authentication
+            GITHUB_TOKEN="${GITHUB_TOKEN}"
+            BRANCH="${CIRCLE_BRANCH}"
+
+            # Fetch the PRs associated with the current branch and check the response
+            PR_RESPONSE=$(curl -s -H "Authorization: token ${GITHUB_TOKEN}" \
+              "https://api.github.com/repos/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/pulls?state=open&head=${CIRCLE_PROJECT_USERNAME}:${BRANCH}")
+            echo "https://api.github.com/repos/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/pulls?state=open&head=${CIRCLE_PROJECT_USERNAME}:${BRANCH}"
+
+            # Check if the response contains valid JSON
+            if ! echo "$PR_RESPONSE" | jq empty; then
+                echo "Failed to parse JSON response."
+                echo "$PR_RESPONSE"
+                exit 1
+            fi
+
+            # Check if we received an array of PRs
+            if ! echo "$PR_RESPONSE" | jq -e '. | type == "array"'; then
+                echo "$PR_RESPONSE"
+                echo "Expected an array of PRs, got something else."
+                exit 1
+            fi
+
+            # Check if the array of PRs is empty
+            PR_COUNT=$(echo "$PR_RESPONSE" | jq '. | length')
+
+            # If no PRs are found, exit gracefully
+            if [ "$PR_COUNT" -eq 0 ]; then
+              echo "No open PRs found. Exiting."
+              echo "false" > ./RUN_MMI_OPTIONAL
+              exit 0
+            fi
+
+            # Extract label names from the PR_RESPONSE
+            LABEL_NAMES=$(echo "$PR_RESPONSE" | jq -r '.[0].labels[].name')
+
+            echo "Labels found: $LABEL_NAMES"
+
+            # Check if "team-mmi" label is present
+            if echo "$LABEL_NAMES" | grep -qw "team-mmi"; then
+              echo "team-mmi tag found."
+              # assign the RUN_MMI_OPTIONAL variable to true
+              echo "true" > ./RUN_MMI_OPTIONAL
+            else
+              echo "team-mmi tag not found."
+              # assign the RUN_MMI_OPTIONAL variable to false
+              echo "false" > ./RUN_MMI_OPTIONAL
+            fi
+      - persist_to_workspace:
+          root: .
+          paths:
+            - RUN_MMI_OPTIONAL
 
   prep-deps:
     executor: node-browsers-medium
@@ -640,6 +716,7 @@ jobs:
       - run: *shallow-git-clone
       - attach_workspace:
           at: .
+      - run: *check-mmi-optional
       - run:
           name: Build MMI extension for Playwright e2e
           command: |
@@ -654,6 +731,7 @@ jobs:
       - persist_to_workspace:
           root: .
           paths:
+            - RUN_MMI_OPTIONAL
             - dist-test-mmi-playwright
             - builds-test-mmi-playwright
       - store_artifacts:
@@ -875,7 +953,7 @@ jobs:
           command: |
             if .circleci/scripts/test-run-e2e.sh
             then
-              timeout 20m yarn test:e2e:chrome --retries 2 --debug
+              timeout 20m yarn test:e2e:chrome --retries 2
             fi
           no_output_timeout: 5m
       - store_artifacts:
@@ -902,7 +980,7 @@ jobs:
           command: |
             if .circleci/scripts/test-run-e2e.sh
             then
-              timeout 20m yarn test:e2e:chrome --retries 2 --debug
+              timeout 20m yarn test:e2e:chrome --retries 2
             fi
           no_output_timeout: 5m
           environment:
@@ -931,7 +1009,7 @@ jobs:
           command: |
             if .circleci/scripts/test-run-e2e.sh
             then
-              timeout 20m yarn test:e2e:chrome --retries 2 --debug || echo "Temporarily suppressing MV3 e2e test failures"
+              timeout 20m yarn test:e2e:chrome --retries 2 || echo "Temporarily suppressing MV3 e2e test failures"
             fi
           no_output_timeout: 5m
       - store_artifacts:
@@ -1009,7 +1087,7 @@ jobs:
           command: |
             if .circleci/scripts/test-run-e2e.sh
             then
-              timeout 20m yarn test:e2e:chrome:rpc --retries 2 --debug --build-type=mmi
+              timeout 20m yarn test:e2e:chrome:rpc --retries 2 --build-type=mmi
             fi
           no_output_timeout: 5m
       - store_artifacts:
@@ -1029,7 +1107,7 @@ jobs:
           command: |
             if .circleci/scripts/test-run-e2e.sh
             then
-              yarn test:e2e:single test/e2e/vault-decryption-chrome.spec.js --browser chrome --retries 2 --debug
+              yarn test:e2e:single test/e2e/vault-decryption-chrome.spec.js --browser chrome --retries 2
             fi
           no_output_timeout: 5m
 
@@ -1051,7 +1129,7 @@ jobs:
           command: |
             if .circleci/scripts/test-run-e2e.sh
             then
-              timeout 20m yarn test:e2e:firefox:flask --retries 2 --debug
+              timeout 20m yarn test:e2e:firefox:flask --retries 2
             fi
           no_output_timeout: 5m
       - store_artifacts:
@@ -1078,7 +1156,7 @@ jobs:
           command: |
             if .circleci/scripts/test-run-e2e.sh
             then
-              timeout 20m yarn test:e2e:chrome:flask --retries 2 --debug
+              timeout 20m yarn test:e2e:chrome:flask --retries 2
             fi
           no_output_timeout: 5m
       - store_artifacts:
@@ -1105,7 +1183,7 @@ jobs:
           command: |
             if .circleci/scripts/test-run-e2e.sh
             then
-              timeout 20m yarn test:e2e:chrome:mmi --retries 2 --debug --build-type=mmi
+              timeout 20m yarn test:e2e:chrome:mmi --retries 2 --build-type=mmi
             fi
           no_output_timeout: 5m
       - store_artifacts:
@@ -1121,6 +1199,7 @@ jobs:
       - run: *shallow-git-clone
       - attach_workspace:
           at: .
+      - run: *check-mmi-optional
       - run:
           name: Move test build to dist
           command: mv ./dist-test-mmi-playwright ./dist
@@ -1172,7 +1251,7 @@ jobs:
           command: |
             if .circleci/scripts/test-run-e2e.sh
             then
-              timeout 20m yarn test:e2e:firefox --retries 2 --debug
+              timeout 20m yarn test:e2e:firefox --retries 2
             fi
           no_output_timeout: 5m
       - store_artifacts:
@@ -1571,4 +1650,4 @@ jobs:
     steps:
       - run:
           name: All Tests Passed
-          command: echo 'weew - everything passed!'
+          command: echo 'whew - everything passed!'
