fix

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -111,9 +111,25 @@ jobs:
     outputs:
       PASSED: ${{ steps.set-output.outputs.PASSED }}
     steps:
+      - name: Check changelog lint status
+        id: changelog-status
+        run: |
+          if [[ "${{ github.ref_name }}" == Version-v* ]]; then
+            echo "Ignoring failure for changelog validation in Version-v branch."
+            echo "IGNORED=true" >> $GITHUB_ENV
+          else
+            echo "IGNORED=false" >> $GITHUB_ENV
+          fi
+
       - name: Set PASSED output
         id: set-output
-        run: echo "PASSED=true" >> "$GITHUB_OUTPUT"
+        run: |
+          if [[ "${{ env.IGNORED }}" == "true" ]]; then
+            echo "PASSED=true" >> "$GITHUB_OUTPUT"
+          else
+            echo "PASSED=false" >> "$GITHUB_OUTPUT"
+            exit 1
+          fi
 
   all-jobs-pass:
     name: All jobs pass
